# 6.2.3 [실습] RNN 기초

In [1]:
import numpy as np

## RNN 텐서플로 코드 구현

In [2]:
import tensorflow as tf
from tensorflow.keras.layers import Input, Dense, SimpleRNN
from tensorflow.keras.models import Model

In [3]:
inputs = Input(shape=(1, 2))

output, state = SimpleRNN(3, return_state=True)(inputs)
model = Model(inputs=inputs, outputs=[output, state])

In [ ]:
data = np.array([[[1, 2]]])

output, state = model.predict(data)
print("output: ", output)
print("state: ", state)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 295ms/step
output:  [[0.5122149  0.56269634 0.96338797]]
state:  [[0.5122149  0.56269634 0.96338797]]


In [ ]:
model.layers[1].weights[0]

<KerasVariable shape=(2, 3), dtype=float32, path=simple_rnn/simple_rnn_cell/kernel>


In [10]:
model.layers[1].weights[1]

<KerasVariable shape=(3, 3), dtype=float32, path=simple_rnn/simple_rnn_cell/recurrent_kernel>

In [11]:
model.layers[1].weights[2]

<KerasVariable shape=(3,), dtype=float32, path=simple_rnn/simple_rnn_cell/bias>

## 텐서플로를 이용한 단어 품사 구분

In [12]:
# I         [1,0,0,0]
# work      [0,1,0,0]
# at        [0,0,1,0]
# google    [0,0,0,1]

data = np.array(
    [
        [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]],
        [[1, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0], [0, 1, 0, 0]],
    ]
)

In [17]:
inputs = Input(shape=(4, 4))

output, state = SimpleRNN(3, return_state=True, return_sequences=True)(inputs)
model = Model(inputs=inputs, outputs=[output, state])

output, state = model.predict(data)

print("I work at google: ", output[0])
print("I google at work: ", output[1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step
I work at google:  [[ 0.22136486 -0.5972894  -0.10483949]
 [-0.42491227  0.69204295 -0.48565823]
 [ 0.30405563 -0.3550673   0.6750606 ]
 [ 0.7833565  -0.08101916 -0.02952401]]
I google at work:  [[ 0.22136486 -0.5972894  -0.10483949]
 [ 0.316886   -0.20901692 -0.37119105]
 [ 0.190918    0.6302231   0.43887362]
 [ 0.0944981   0.2875641   0.5095254 ]]


In [18]:
print("I work at google: ", state[0])
print("I google at work: ", state[1])

I work at google:  [ 0.7833565  -0.08101916 -0.02952401]
I google at work:  [0.0944981 0.2875641 0.5095254]
